In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("../data_selected/car_hacking/tabddpm_car-hacking-rpm-bits_20231212164000615.csv")

/var/folders/5t/wpyxbs_903nbb1sr78d2hhnc0000gn/T/ipykernel_19939/2584380953.py:1: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data_selected/car_hacking/tabddpm_car-hacking-rpm-bits_20231212164000615.csv")

In [10]:
df['DATA_3'].map(type).unique()

array([<class 'str'>, <class 'float'>], dtype=object)

In [11]:
df[df['DATA_3'].apply(lambda x: isinstance(x, float))]

,Timestamp,CAN_ID,DLC,DATA_0,DATA_1,DATA_2,DATA_3,DATA_4,DATA_5,DATA_6,DATA_7,Label
2,1.478191e+09,04c0,2,00,00,NaN,NaN,NaN,NaN,NaN,NaN,R
4,1.478191e+09,04c0,2,00,00,NaN,NaN,NaN,NaN,NaN,NaN,R
6,1.478191e+09,04c0,2,00,00,NaN,NaN,NaN,NaN,NaN,NaN,R
8,1.478191e+09,0316,2,45,29,NaN,NaN,NaN,NaN,NaN,NaN,R
11,1.478191e+09,04c0,2,00,00,NaN,NaN,NaN,NaN,NaN,NaN,R
...,...,...,...,...,...,...,...,...,...,...,...,...
699995,1.478201e+09,0131,8,f3,7f,0.0,0.0,1d,7f,02,ff,R
699996,1.478201e+09,0740,2,00,00,NaN,NaN,NaN,NaN,NaN,NaN,T
699997,1.478201e+09,0300,2,04,00,NaN,NaN,NaN,NaN,NaN,NaN,T
699998,1.478201e+09,0740,2,00,00,NaN,NaN,NaN,NaN,NaN,NaN,R
699999,1.478201e+09,0300,2,04,00,NaN,NaN,NaN,NaN,NaN,NaN,T

In [8]:
df['DATA_2'].to_list()

[0.0,
 24.0,
 nan,
 24.0,
 nan,
 24.0,
 nan,
 0.0,
 nan,
 0.0,
 0.0,
 nan,
 24.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 24.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 24.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 24.0,
 24.0,
 nan,
 24.0,
 nan,
 nan,
 0.0,
 nan,
 24.0,
 24.0,
 nan,
 24.0,
 nan,
 0.0,
 24.0,
 24.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 24.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 24.0,
 0.0,
 24.0,
 nan,
 24.0,
 0.0,
 24.0,
 nan,
 0.0,
 nan,
 nan,
 0.0,
 nan,
 nan,
 nan,
 0.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 24.0,
 24.0,
 24.0,
 nan,
 0.0,
 0.0,
 24.0,
 24.0,
 nan,
 nan,
 24.0,
 nan,
 nan,
 nan,
 0.0,
 nan,
 nan,
 24.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 24.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 24.0,
 nan,
 24.0,
 nan,
 nan,
 0.0,
 nan,
 24.0,
 nan,
 0.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 0.0,
 24.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 24.0,
 nan,
 nan,
 nan,
 nan,
 24.0,
 24.0,
 nan,
 nan,
 0.0,
 24.0,
 nan,
 nan,
 nan,
 0.0,
 nan,
 nan,
 0.0,
 nan,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 nan,
 0.0,
 nan,
 nan,
 nan,
 nan,
 24.0,
 0.0,
 nan,
 24.0,
 nan,
 nan,
 nan,
 24.0,
 nan,
 nan,
 24.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 0.0,
 nan,
 nan,
 0.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 nan,
 0.0,
 0.0,
 24.0,
 nan,
 0.0,
 nan,
 nan,
 nan,
 24.0,
 24.0,
 nan,
 nan,
 nan,
 0.0,
 nan,
 0.0,
 nan,
 0.0,
 0.0,
 nan,
 0.0,
 24.0,
 nan,
 nan,
 0.0,
 0.0,
 nan,
 24.0,
 nan,
 24.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 0.0,
 nan,
 0.0,
 24.0,
 24.0,
 0.0,
 nan,
 nan,
 nan,
 24.0,
 nan,
 nan,
 0.0,
 nan,
 0.0,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 nan,
 0.0,
 nan,
 0.0,
 nan,
 0.0,
 nan,
 0.0,
 0.0,
 0.0,
 nan,
 0.0,
 nan,
 nan,
 0.0,
 24.0,
 nan,
 nan,
 0.0,
 nan,
 nan,
 nan,
 0.0,
 nan,
 nan,
 0.0,
 0.0,
 nan,
 nan,
 24.0,
 nan,
 nan,
 nan,
 24.0,
 nan,
 nan,
 24.0,
 0.0,
 0.0,
 nan,
 nan,
 24.0,
 nan,
 nan,
 nan,
 24.0,
 24.0,
 0.0,
 nan,
 nan,
 0.0,
 nan,
 0.0,
 nan,
 0.0,
 nan,
 nan,
 0.0,
 0.0,
 nan,
 0.0,
 nan,
 nan,
 24.0,
 nan,
 24.0,
 24.0,
 nan,
 nan,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 24.0,
 nan,
 24.0,
 0.0,
 24.0,
 24.0,
 24.0,
 24.0,
 0.0,
 0.0,
 0.0,
 nan,
 0.0,
 24.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 24.0,
 24.0,
 0.0,
 nan,
 0.0,
 nan,
 24.0,
 nan,
 24.0,
 nan,
 nan,
 nan,
 24.0,
 nan,
 24.0,
 0.0,
 nan,
 0.0,
 nan,
 0.0,
 24.0,
 0.0,
 nan,
 0.0,
 nan,
 nan,
 nan,
 24.0,
 0.0,
 nan,
 nan,
 0.0,
 nan,
 0.0,
 nan,
 nan,
 nan,
 24.0,
 24.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 24.0,
 nan,
 0.0,
 24.0,
 0.0,
 0.0,
 nan,
 24.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 0.0,
 24.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 nan,
 24.0,
 nan,
 24.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 0.0,
 nan,
 nan,
 nan,
 0.0,
 nan,
 24.0,
 0.0,
 24.0,
 nan,
 nan,
 0.0,
 nan,
 nan,
 nan,
 24.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 nan,
 0.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 0.0,
 nan,
 nan,
 nan,
 24.0,
 24.0,
 24.0,
 0.0,
 nan,
 nan,
 24.0,
 nan,
 nan,
 24.0,
 nan,
 nan,
 nan,
 24.0,
 0.0,
 nan,
 nan,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 24.0,
 nan,
 nan,
 24.0,
 nan,
 0.0,
 nan,
 nan,
 nan,
 0.0,
 nan,
 24.0,
 nan,
 nan,
 nan,
 0.0,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 24.0,
 24.0,
 0.0,
 nan,
 24.0,
 24.0,
 nan,
 24.0,
 24.0,
 nan,
 nan,
 nan,
 24.0,
 24.0,
 nan,
 24.0,
 24.0,
 nan,
 24.0,
 nan,
 24.0,
 nan,
 nan,
 nan,
 24.0,
 nan,
 24.0,
 nan,
 24.0,
 nan,
 nan,
 24.0,
 0.0,
 0.0,
 24.0,
 nan,
 24.0,
 nan,
 nan,
 0.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 24.0,
 nan,
 nan,
 24.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 24.0,
 nan,
 nan,
 nan,
 0.0,
 nan,
 nan,
 24.0,
 nan,
 nan,
 nan,
 0.0,
 nan,
 0.0,
 nan,
 24.0,
 0.0,
 0.0,
 nan,
 24.0,
 nan,
 0.0,
 nan,
 0.0,
 nan,
 nan,
 nan,
 nan,
 24.0,
 24.0,
 nan,
 nan,
 nan,
 0.0,
 nan,
 nan,
 0.0,
 24.0,
 nan,
 nan,
 nan,
 nan,
 24.0,
 0.0,
 24.0,
 nan,
 nan,
 nan,
 nan,
 24.0,
 nan,
 nan,
 0.0,
 nan,
 24.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 nan,
 nan,
 0.0,
 nan,
 nan,
 0.0,
 24.0,
 0.0,
 nan,
 0.0,
 nan,
 0.0,
 0.0,
 nan,
 nan,
 24.0,
 nan,
 0.0,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 24.0,
 0.0,
 nan,
 24.0,
 nan,
 24.0,
 24.0,
 0.0,
 nan,
 nan,
 24.0,
 0.0,
 nan,
 0.0,
 24.0,
 nan,
 nan,
 0.0,
 0.0,
 24.0,
 nan,
 24.0,
 24.0,
 nan,
 nan,
 nan,
 nan,
 24.0,
 nan,
 nan,
 0.0,
 nan,
 24.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 0.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 0.0,
 nan,
 0.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 24.0,
 nan,
 0.0,
 0.0,
 24.0,
 0.0,
 nan,
 nan,
 nan,
 24.0,
 nan,
 0.0,
 nan,
 0.0,
 0.0,
 nan,
 0.0,
 24.0,
 24.0,
 24.0,
 nan,
 nan,
 nan,
 0.0,
 nan,
 nan,
 24.0,
 24.0,
 nan,
 24.0,
 nan,
 24.0,
 0.0,
 nan,
 nan,
 0.0,
 nan,
 nan,
 24.0,
 nan,
 24.0,
 0.0,
 nan,
 nan,
 0.0,
 nan,
 24.0,
 nan,
 24.0,
 0.0,
 0.0,
 24.0,
 24.0,
 nan,
 24.0,
 nan,
 nan,
 0.0,
 nan,
 nan,
 0.0,
 0.0,
 24.0,
 nan,
 24.0,
 24.0,
 nan,
 nan,
 nan,
 nan,
 24.0,
 nan,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 24.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 0.0,
 24.0,
 nan,
 0.0,
 nan,
 0.0,
 24.0,
 0.0,
 24.0,
 24.0,
 nan,
 0.0,
 24.0,
 nan,
 24.0,
 nan,
 0.0,
 24.0,
 nan,
 0.0,
 nan,
 0.0,
 24.0,
 nan,
 nan,
 0.0,
 24.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 0.0,
 nan,
 nan,
 24.0,
 0.0,
 0.0,
 24.0,
 nan,
 24.0,
 0.0,
 nan,
 24.0,
 nan,
 24.0,
 nan,
 0.0,
 nan,
 0.0,
 0.0,
 nan,
 nan,
 24.0,
 0.0,
 0.0,
 0.0,
 24.0,
 24.0,
 24.0,
 nan,
 nan,
 0.0,
 24.0,
 24.0,
 24.0,
 nan,
 nan,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 24.0,
 nan,
 0.0,
 nan,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 24.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 24.0,
 24.0,
 24.0,
 24.0,
 nan,
 0.0,
 24.0,
 nan,
 nan,
 nan,
 0.0,
 nan,
 0.0,
 nan,
 24.0,
 nan,
 0.0,
 24.0,
 0.0,
 0.0,
 nan,
 24.0,
 24.0,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 24.0,
 nan,
 nan,
 nan,
 nan,
 24.0,
 24.0,
 nan,
 nan,
 nan,
 24.0,
 0.0,
 24.0,
 24.0,
 nan,
 24.0,
 nan,
 nan,
 0.0,
 nan,
 nan,
 0.0,
 24.0,
 nan,
 nan,
 nan,
 24.0,
 24.0,
 0.0,
 nan,
 0.0,
 nan,
 24.0,
 nan,
 nan,
 0.0,
 nan,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 24.0,
 nan,
 24.0,
 24.0,
 0.0,
 24.0,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 nan,
 nan,
 0.0,
 0.0,
 nan,
 24.0,
 nan,
 0.0,
 nan,
 nan,
 ...]

In [9]:
df['DATA_2'].apply(lambda x: isinstance(x, float))

0         True
1         True
2         True
3         True
4         True
          ...
699995    True
699996    True
699997    True
699998    True
699999    True
Name: DATA_2, Length: 700000, dtype: bool

In [12]:
df.dtypes

Timestamp    float64
CAN_ID        object
DLC            int64
DATA_0        object
DATA_1        object
DATA_2        object
DATA_3        object
DATA_4        object
DATA_5        object
DATA_6        object
DATA_7        object
Label         object
dtype: object

In [19]:
import numpy as np

df = pd.DataFrame({
    'col1': ['00', '24', '00', np.nan, '24', '00'],
    'col2': [2, 1, 9, 8, 7, 4],
    'col3': [0, 1, 9, 4, 2, 3],
    'col4': ['a', 'B', 'c', 'D', 'e', 'F']
})

In [15]:
df

  col1  col2  col3 col4
0   00     2     0    a
1   24     1     1    B
2   00     9     9    c
3  NaN     8     4    D
4   24     7     2    e
5   00     4     3    F

In [22]:
new_df = df.sort_values(by='col3')

In [23]:
new_df

  col1  col2  col3 col4
0   00     2     0    a
1   24     1     1    B
4   24     7     2    e
5   00     4     3    F
3  NaN     8     4    D
2   00     9     9    c

In [24]:
new_df.dtypes

col1    object
col2     int64
col3     int64
col4    object
dtype: object

In [25]:
new_df.to_csv('test.csv', index=False)

In [31]:
new_df = pd.read_csv('test.csv', dtype={'col1': object})

In [32]:
new_df

  col1  col2  col3 col4
0   00     2     0    a
1   24     1     1    B
2   24     7     2    e
3   00     4     3    F
4  NaN     8     4    D
5   00     9     9    c